trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'YourServiceConnection'
    subscriptionId: 'bbe586c3-363a-4dc7-9f08-3ee4a898c1f4'
    resourceGroupName: 'yaniv-assignement'
    location: 'East US'
    csmFile: '$(System.DefaultWorkingDirectory)/storageAccount.json'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'YourServiceConnection'
    subscriptionId: 'bbe586c3-363a-4dc7-9f08-3ee4a898c1f4'
    resourceGroupName: 'yaniv-assignement'
    location: 'East US'
    csmFile: '$(System.DefaultWorkingDirectory)/virtualMachine.json'